import json
import shutil
from collections import defaultdict
from datetime import datetime
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
VALIDATED_DIR = PROJECT_ROOT / "data" / "validated"
OUTPUT_DIR = PROJECT_ROOT / "data" / "s3_partitioned" / "raw"


DATASETS = {
    "customers": {
        "input_file": "customers.json",
        "date_field": "created_at",
    },
    "transactions": {
        "input_file": "transactions.json",
        "date_field": "transaction_timestamp",
    },
    "fraud_signals": {
        "input_file": "fraud_signals.json",
        "date_field": "score_timestamp",
    },
    "disputes": {
        "input_file": "disputes.json",
        "date_field": "opened_date",
    },
    "chargeback_outcomes": {
        "input_file": "chargeback_outcomes.json",
        "date_field": "resolved_date",
    },
}


def parse_datetime(value: str) -> datetime:
    """
    Parses common timestamp strings generated by the synthetic data script.
    """
    if not value:
        raise ValueError("Missing date value")

    value = str(value).replace("Z", "")

    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return datetime.strptime(value[:19], "%Y-%m-%d %H:%M:%S")


def load_json_lines(file_path: Path):
    """
    Reads newline-delimited JSON.
    Each line is one JSON record.
    """
    with file_path.open("r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()
            if line:
                yield json.loads(line)


def write_partitioned_dataset(dataset_name: str, input_file: str, date_field: str):
    input_path = VALIDATED_DIR / input_file

    if not input_path.exists():
        raise FileNotFoundError(
            f"Missing validated input file: {input_path}. "
            "Run scripts/validate_data_contracts.py before partitioning."
        )

    partitions = defaultdict(list)

    for record in load_json_lines(input_path):
        date_value = record.get(date_field)

        if not date_value:
            continue

        parsed_date = parse_datetime(date_value)
        year = parsed_date.year
        month = f"{parsed_date.month:02d}"

        partitions[(year, month)].append(record)

    total_records = 0

    for (year, month), records in partitions.items():
        partition_dir = OUTPUT_DIR / dataset_name / f"year={year}" / f"month={month}"
        partition_dir.mkdir(parents=True, exist_ok=True)

        output_file = partition_dir / f"{dataset_name}_{year}_{month}.json"

        with output_file.open("w", encoding="utf-8") as file:
            for record in records:
                file.write(json.dumps(record) + "\n")

        total_records += len(records)
        print(f"{dataset_name}: wrote {len(records)} records to {output_file}")

    print(f"{dataset_name}: {total_records} total records partitioned")


def main():
    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Writing partitioned files to: {OUTPUT_DIR}")

    for dataset_name, config in DATASETS.items():
        write_partitioned_dataset(
            dataset_name=dataset_name,
            input_file=config["input_file"],
            date_field=config["date_field"],
        )

    print("S3 partitioned files generated successfully.")


if __name__ == "__main__":
    main()