-- Purpose:
-- Reload Snowflake RAW tables from the partitioned AWS S3 raw zone.
--
-- Strategy:
-- This is a controlled full reload.
-- Each RAW table is truncated before COPY INTO runs.
-- This prevents duplicate rows when the same S3 files are loaded again.
--
-- Flow:
-- S3_RAW_STAGE
--   -> RAW_CUSTOMERS
--   -> RAW_TRANSACTIONS
--   -> RAW_FRAUD_SIGNALS
--   -> RAW_DISPUTES
--   -> RAW_CHARGEBACK_OUTCOMES

USE ROLE ACCOUNTADMIN;
USE DATABASE FRAUD_DISPUTE_DB;
USE SCHEMA RAW;

TRUNCATE TABLE RAW_CUSTOMERS;
TRUNCATE TABLE RAW_TRANSACTIONS;
TRUNCATE TABLE RAW_FRAUD_SIGNALS;
TRUNCATE TABLE RAW_DISPUTES;
TRUNCATE TABLE RAW_CHARGEBACK_OUTCOMES;

COPY INTO RAW_CUSTOMERS (raw_record)
FROM (
  SELECT $1
  FROM @S3_RAW_STAGE/customers/
)
FILE_FORMAT = (FORMAT_NAME = JSON_LINES_FORMAT)
PATTERN = '.*[.]json'
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_TRANSACTIONS (raw_record)
FROM (
  SELECT $1
  FROM @S3_RAW_STAGE/transactions/
)
FILE_FORMAT = (FORMAT_NAME = JSON_LINES_FORMAT)
PATTERN = '.*[.]json'
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_FRAUD_SIGNALS (raw_record)
FROM (
  SELECT $1
  FROM @S3_RAW_STAGE/fraud_signals/
)
FILE_FORMAT = (FORMAT_NAME = JSON_LINES_FORMAT)
PATTERN = '.*[.]json'
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_DISPUTES (raw_record)
FROM (
  SELECT $1
  FROM @S3_RAW_STAGE/disputes/
)
FILE_FORMAT = (FORMAT_NAME = JSON_LINES_FORMAT)
PATTERN = '.*[.]json'
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_CHARGEBACK_OUTCOMES (raw_record)
FROM (
  SELECT $1
  FROM @S3_RAW_STAGE/chargeback_outcomes/
)
FILE_FORMAT = (FORMAT_NAME = JSON_LINES_FORMAT)
PATTERN = '.*[.]json'
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';
