-- Purpose:
-- Example least-privilege Snowflake role setup for the fraud dispute analytics pipeline.
--
-- Run this with an admin role such as ACCOUNTADMIN or SECURITYADMIN.
-- Normal pipeline execution should use FRAUD_DISPUTE_ROLE, not ACCOUNTADMIN.
--
-- Replace YOUR_SNOWFLAKE_USER before executing.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS FRAUD_DISPUTE_ROLE;

GRANT ROLE FRAUD_DISPUTE_ROLE TO USER YOUR_SNOWFLAKE_USER;

GRANT USAGE ON WAREHOUSE FRAUD_DISPUTE_WH
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT USAGE ON DATABASE FRAUD_DISPUTE_DB
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT USAGE ON SCHEMA FRAUD_DISPUTE_DB.RAW
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT USAGE ON SCHEMA FRAUD_DISPUTE_DB.STAGING
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT USAGE ON SCHEMA FRAUD_DISPUTE_DB.MARTS
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT USAGE ON SCHEMA FRAUD_DISPUTE_DB.MONITORING
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT USAGE ON FILE FORMAT FRAUD_DISPUTE_DB.RAW.JSON_LINES_FORMAT
TO ROLE FRAUD_DISPUTE_ROLE;

-- Required for COPY INTO from the external stage.
-- Run after S3_RAW_STAGE has been created.
GRANT USAGE ON STAGE FRAUD_DISPUTE_DB.RAW.S3_RAW_STAGE
TO ROLE FRAUD_DISPUTE_ROLE;

-- RAW reload permissions.
GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA FRAUD_DISPUTE_DB.RAW
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA FRAUD_DISPUTE_DB.RAW
TO ROLE FRAUD_DISPUTE_ROLE;

-- dbt model build permissions.
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA FRAUD_DISPUTE_DB.STAGING
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA FRAUD_DISPUTE_DB.MARTS
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA FRAUD_DISPUTE_DB.MONITORING
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FRAUD_DISPUTE_DB.STAGING
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FRAUD_DISPUTE_DB.MARTS
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FRAUD_DISPUTE_DB.MONITORING
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA FRAUD_DISPUTE_DB.STAGING
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA FRAUD_DISPUTE_DB.MARTS
TO ROLE FRAUD_DISPUTE_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA FRAUD_DISPUTE_DB.MONITORING
TO ROLE FRAUD_DISPUTE_ROLE;