CREATE WAREHOUSE IF NOT EXISTS FRAUD_DISPUTE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS FRAUD_DISPUTE_DB;

USE WAREHOUSE FRAUD_DISPUTE_WH;
USE DATABASE FRAUD_DISPUTE_DB;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS MONITORING;