-- Purpose:
-- Validate RAW table row counts after loading from S3.

USE ROLE ACCOUNTADMIN;
USE DATABASE FRAUD_DISPUTE_DB;
USE SCHEMA RAW;

SELECT 'RAW_CHARGEBACK_OUTCOMES' AS table_name, COUNT(*) AS row_count FROM RAW_CHARGEBACK_OUTCOMES
UNION ALL
SELECT 'RAW_CUSTOMERS', COUNT(*) FROM RAW_CUSTOMERS
UNION ALL
SELECT 'RAW_DISPUTES', COUNT(*) FROM RAW_DISPUTES
UNION ALL
SELECT 'RAW_FRAUD_SIGNALS', COUNT(*) FROM RAW_FRAUD_SIGNALS
UNION ALL
SELECT 'RAW_TRANSACTIONS', COUNT(*) FROM RAW_TRANSACTIONS
ORDER BY table_name;
